server:
  port: 8123
  servlet:
    context-path: /api

# 用于单元测试的ak sk
xiapi:
  client:
    access-key: 5f9aea1a6d378f637204d6df1094c578
    secret-key: 7648bec14e20baecb065b14c90c2d16a

# ai服务ak与sk
yuapi:
  client:
    access-key:
    secret-key:

# 星火大模型api调用密钥
spark:
  client:
    appid:
    apiKey:
    apiSecret: